// frameworks/remix/app/components/user-status.tsx
import { Form } from "react-router";
import { TokenPanels } from "./token-panels";

type User = {
  idTokenClaims: Record<string, unknown>;
  accessTokenClaims: Record<string, unknown>;
};

const buttonClasses =
  "cursor-pointer rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600";

export function UserStatus({ user }: { user: User | null }) {
  return (
    <div>
      <div className="pb-8 text-xl italic">Your current status is:</div>
      {user ? (
        <>
          <div className="mb-2 text-2xl text-p2blue-700">Authenticated</div>
          <div className="mb-6 text-p2blue-700">
            <div>{String(user.idTokenClaims.name ?? "")}</div>
            <div>{String(user.idTokenClaims.email ?? "")}</div>
          </div>
          <Form method="post" action="/logout" reloadDocument>
            <button type="submit" className={buttonClasses}>
              Log out
            </button>
          </Form>
          <TokenPanels
            accessTokenClaims={user.accessTokenClaims}
            idTokenClaims={user.idTokenClaims}
          />
        </>
      ) : (
        <>
          <div className="mb-6 text-2xl text-p2blue-700">
            Not authenticated.
          </div>
          <Form method="post" action="/auth/keycloak" reloadDocument>
            <button type="submit" className={buttonClasses}>
              Log in
            </button>
          </Form>
        </>
      )}
    </div>
  );
}

// frameworks/nuxt/keycloak-js/app/components/UserStatus.vue
<script setup lang="ts">
const { state, login, logout } = useKeycloak();

const buttonClasses =
  "cursor-pointer rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600";
</script>

<template>
  <div>
    <div class="pb-8 text-xl italic">Your current status is:</div>
    <template v-if="state.authenticated">
      <div class="mb-2 text-2xl text-p2blue-700">Authenticated</div>
      <div class="mb-6 text-p2blue-700">
        <div>{{ state.idTokenParsed?.name }}</div>
        <div>{{ state.idTokenParsed?.email }}</div>
      </div>
      <button type="button" :class="buttonClasses" @click="logout()">
        Log out
      </button>
      <TokenPanels
        :access-token="state.tokenParsed"
        :id-token="state.idTokenParsed"
      />
    </template>
    <template v-else-if="state.error">
      <div class="mb-2 text-2xl text-p2blue-700">Authentication error.</div>
      <div class="mb-6">{{ state.error }}</div>
      <button type="button" :class="buttonClasses" @click="login()">
        Log in
      </button>
    </template>
    <template v-else>
      <div class="mb-6 text-2xl text-p2blue-700">Not authenticated.</div>
      <button type="button" :class="buttonClasses" @click="login()">
        Log in
      </button>
    </template>
  </div>
</template>
