// frameworks/nuxt/keycloak-js/components/User.vue
<script setup lang="ts">
import { useKeycloak } from "../composables/keycloak-c";
import TokenComponent from "./Token.vue";

const { keycloak, authState } = useKeycloak();

function login() {
  keycloak.login();
}

function logout() {
  keycloak.logout();
}
</script>

<template>
  <div>
    <div v-if="authState === 'unAuthenticated'">
      <div class="mb-6 text-p2blue-700 text-2xl">Not authenticated.</div>
      <button
        class="rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
        @click="login()"
      >
        Log in
      </button>
    </div>
    <div v-if="authState === 'authenticated'">
      <div class="mb-2 text-p2blue-700 text-2xl">Authenticated</div>
      <div class="mb-6 text-p2blue-700 text-md">
        <div>{{ keycloak.tokenParsed?.email }}</div>
        <div>{{ keycloak.tokenParsed?.sub }}</div>
      </div>
      <button
        class="rounded-md bg-indigo-500 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
        @click="logout()"
      >
        Log out
      </button>
      <TokenComponent :user="keycloak" />
    </div>
    <div>
      <div v-if="authState === 'error'" class="mb-6 text-p2blue-700 text-2xl">
        Authentication Error.
      </div>
    </div>
  </div>
</template>

// frameworks/spring-boot-keycloak/angularclient/src/app/components/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { OAuthService } from 'angular-oauth2-oidc';
import { Subscription } from 'rxjs';
import { AuthService } from '../../service/auth.service';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
})
export class UserComponent implements OnInit {
  isLoggedIn: boolean = false;
  private authSubscription: Subscription;
  userInfo: any;

  buttonClasses =
    'rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600';

  constructor(
    private oauthService: OAuthService,
    private authService: AuthService
  ) {}

  signIn() {
    return this.authService.signIn();
  }

  signOut() {
    this.authService.signOut();
  }

  ngOnInit(): void {
    this.userInfo = this.authService.getUserInfo();
    this.isLoggedIn = this.oauthService.hasValidAccessToken();

    this.authSubscription = this.oauthService.events.subscribe((event) => {
      if (event.type === 'token_received' || event.type === 'token_expires') {
        this.isLoggedIn = this.oauthService.hasValidAccessToken();
      }
    });
  }

  ngOnDestroy(): void {
    if (this.authSubscription) {
      this.authSubscription.unsubscribe();
    }
  }
}

<div *ngIf="isLoggedIn">
  <!-- Content for logged-in users -->
  <div class="mb-2 text-p2blue-700 text-2xl">Authenticated</div>
  <div class="mb-6 text-p2blue-700 text-md">
    <div *ngIf="userInfo">
      <p><span class="font-bold">Username</span>: {{ userInfo.username }}</p>
      <p><span class="font-bold">Email</span>: {{ userInfo.email }}</p>
      <p><span class="font-bold">Roles</span>: {{ userInfo.roles }}</p>
    </div>
  </div>
  <Button [class]="buttonClasses" (click)="signOut()">Sign Out</Button>
</div>
<div *ngIf="!isLoggedIn">
  <div class="mb-6 text-p2blue-700 text-2xl">Not authenticated.</div>
  <Button [class]="buttonClasses" (click)="signIn()">Sign In</Button>
</div>
