// frameworks/sveltekit/src/components/user.svelte
<script lang="ts">
  interface User {
    status: boolean;
    user?: {
      name?: string;
      email?: string;
    };
  }

  export let data: User;

  import LoginButton from "./login_button.svelte";
  import LogoutButton from "./logout_button.svelte";
  import { jwtDecode } from "jwt-decode";
  import { onMount } from "svelte";

  function stringifyToken(token: string) {
    return JSON.stringify(jwtDecode(token), null, 2);
  }

  let idToken = "";
  let accessToken = "";
  let refreshToken = "";

  onMount(() => {
    if (data && data.user) {
      idToken = stringifyToken(data.user.idToken);
      accessToken = stringifyToken(data.user.accessToken);
      refreshToken = stringifyToken(data.user.refreshToken);
    }
  });
</script>

<div>
  <div class="text-xl pb-8 italic">Your current status is:</div>
  {#if data.status}
    <div>
      <div class="mb-2 text-p2blue-700 text-2xl">Authenticated</div>
      <div class="mb-6 text-p2blue-700 text-md">
        <div>{data.user?.email}</div>
        <div>{data.user?.name}</div>
      </div>
      <LogoutButton />

      <div>
        <div class="mt-4 text-left">
          <div class="mt-2">
            <label
              for="accessToken"
              class="block text-sm font-semibold leading-6 text-gray-900"
            >
              Access Token
            </label>

            <textarea
              rows="6"
              name="accessToken"
              id="accessToken"
              class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
              bind:value={accessToken}
            ></textarea>
          </div>
          <div class="mt-2">
            <label
              for="idToken"
              class="block text-sm font-semibold leading-6 text-gray-900"
            >
              Id Token
            </label>

            <textarea
              rows="6"
              name="idToken"
              id="idToken"
              class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
              bind:value={idToken}
            ></textarea>
          </div>
          <div class="mt-2">
            <label
              for="refreshToken"
              class="block text-sm font-semibold leading-6 text-gray-900"
            >
              Refresh Token
            </label>

            <textarea
              rows="6"
              name="refreshToken"
              id="refreshToken"
              class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
              bind:value={refreshToken}
            ></textarea>
          </div>
        </div>
      </div>
    </div>
  {:else}
    <div>
      <div class="mb-6 text-p2blue-700 text-2xl">Not authenticated.</div>
      <LoginButton />
    </div>
  {/if}
</div>

// frameworks/angular/src/app/user/user.component.ts
import { jwtDecode } from 'jwt-decode';
import { Component } from '@angular/core';
import { OAuthService } from 'angular-oauth2-oidc';
import { authCodeFlowConfig } from '../auth.config';
import { NgIf } from '@angular/common';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-user',
  standalone: true,
  imports: [NgIf],
  templateUrl: './user.component.html',
  styleUrl: './user.component.css',
})
export class UserComponent {
  buttonClasses =
    'rounded-md bg-indigo-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600';

  constructor(private oauthService: OAuthService) {
    this.oauthService.configure(authCodeFlowConfig);

    this.oauthService.loadDiscoveryDocumentAndTryLogin();
    this.oauthService.setupAutomaticSilentRefresh();

    this.oauthService.events
      .pipe(filter((e) => e.type === 'token_received'))
      .subscribe((_) => this.oauthService.loadUserProfile());
  }

  signIn() {
    return this.oauthService.initLoginFlow();
  }

  signOut() {
    return this.oauthService.logOut();
  }

  private decodeAndStringifyToken(token: any) {
    return JSON.stringify(jwtDecode(token), null, 2);
  }

  get email(): string {
    const claims = this.oauthService.getIdentityClaims();
    if (!claims) return '';
    return claims['email'];
  }

  get userName(): string {
    const claims = this.oauthService.getIdentityClaims();
    if (!claims) return '';
    return claims['given_name'];
  }

  get idToken(): string {
    const token = this.oauthService.getIdToken();
    if (token) {
      return this.decodeAndStringifyToken(token);
    }
    return '';
  }

  get refreshToken(): string {
    const token = this.oauthService.getRefreshToken();
    if (token) {
      return this.decodeAndStringifyToken(token);
    }
    return '';
  }

  get accessToken(): string {
    const token = this.oauthService.getAccessToken();
    if (token) {
      return this.decodeAndStringifyToken(token);
    }
    return '';
  }
}

<div *ngIf="idToken">
  <!-- Content for logged-in users -->
  <div class="mb-2 text-p2blue-700 text-2xl">Authenticated</div>
  <div class="mb-6 text-p2blue-700 text-md">
    <div>
      <p><span class="font-bold">Username</span>: {{ userName }}</p>
      <p><span class="font-bold">Email</span>: {{ email }}</p>
    </div>
    <div>
      <div class="mt-4 text-left">
        <div class="mt-2">
          <label
            for="accessToken"
            class="block text-sm font-semibold leading-6 text-gray-900"
          >
            Access Token
          </label>

          <textarea
            rows="6"
            name="accessToken"
            id="accessToken"
            class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
            value="{{ accessToken }}"
          ></textarea>
        </div>
        <div class="mt-2">
          <label
            for="idToken"
            class="block text-sm font-semibold leading-6 text-gray-900"
          >
            Id Token
          </label>

          <textarea
            rows="6"
            name="idToken"
            id="idToken"
            class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
            value="{{ idToken }}"
          ></textarea>
        </div>
        <div class="mt-2">
          <label
            for="refreshToken"
            class="block text-sm font-semibold leading-6 text-gray-900"
          >
            Refresh Token
          </label>

          <textarea
            rows="6"
            name="refreshToken"
            id="refreshToken"
            class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 bg-purple-200/50"
            value="{{ refreshToken }}"
          ></textarea>
        </div>
      </div>
    </div>
  </div>
  <Button [class]="buttonClasses" (click)="signOut()">Sign Out</Button>
</div>
<div *ngIf="!idToken">
  <div class="mb-6 text-p2blue-700 text-2xl">Not authenticated.</div>
  <Button [class]="buttonClasses" (click)="signIn()">Sign In</Button>
</div>
